### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by guillaumemorin** [slowpath/react-native-google-app-invites#1]
Hi Ladislav,

I'm trying to build my app with react-native-google-app-invites but on build i'm receiving the error below, do you have an idea on what could be the reason of this? Thx in advance!

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  > A problem occurred configuring project ':react-native-google-app-invites'.
  > Could not resolve all dependencies for configuration ':react-native-google-app-invites:_debugCompile'.
    > Could not find com.google.android.gms:play-services-appinvite:8.3.0.
      Searched in the following locations:
          file:/Users/guillaumemorin/.m2/repository/com/google/android/gms/play-services-appinvite/8.3.0/play-services-appinvite-8.3.0.pom
          file:/Users/guillaumemorin/.m2/repository/com/google/android/gms/play-services-appinvite/8.3.0/play-services-appinvite-8.3.0.jar
          https://jcenter.bintray.com/com/google/android/gms/play-services-appinvite/8.3.0/play-services-appinvite-8.3.0.pom
          https://jcenter.bintray.com/com/google/android/gms/play-services-appinvite/8.3.0/play-services-appinvite-8.3.0.jar
          file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-appinvite/8.3.0/play-services-appinvite-8.3.0.pom
          file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-appinvite/8.3.0/play-services-appinvite-8.3.0.jar

**Comment by iamladi** [comment]
Hey @guillaumemorin,

here's what you need to do:

1) run on terminal `android` (which will start Android SDK Manager)
2) In `Extras` folder install `Google Repository`

After that you should be good to go. Let me know if that worked for you.

**Comment by guillaumemorin** [comment]
hi @martincik 

Thanks a lot for your quick answer! 
You're right, Google Repository install solve the problem !

But I now have : 

/Users/guillaumemorin/reactnative/FingerFrame/android/app/src/main/java/com/fingerframe/MainActivity.java:14: error: package co.apptailor.googleappinvites does not exist
import co.apptailor.googleappinvites.RNGoogleAppInvitesModule;
                                    ^
/Users/guillaumemorin/reactnative/FingerFrame/android/app/src/main/java/com/fingerframe/MainActivity.java:15: error: package co.apptailor.googleappinvites does not exist
import co.apptailor.googleappinvites.RNGoogleAppInvitesPackage;

**Comment by guillaumemorin** [comment]
Oh ok, I think this is : 

import com.slowpath.googleappinvites.RNGoogleAppInvitesModule;
import com.slowpath.googleappinvites.RNGoogleAppInvitesPackage;

instead...right ?

**Comment by iamladi** [comment]
Yes, that’s right. Sorry didn’t have time to respond yesterday. :)

**Comment by guillaumemorin** [comment]
No problem @martincik ! Thx a lot for your answer. I've made a pull request to update the README with correct imports: https://github.com/slowpath/react-native-google-app-invites/pull/2

Now I can build the app without problem, thx!. But I still have an error on import:

Requiring unknown module "react-native-google-app-invites/index.android.js"

 when i use

var GoogleAppInvites = require('react-native-google-app-invites');

**Comment by iamladi** [comment]
@guillaumemorin Can you post here your packages.json file, to have a look at the versions?

**Comment by guillaumemorin** [comment]
"dependencies": {
    "react-native": "^0.17.0",
    "react-native-android-statusbar": "^0.1.1",
    "react-native-camera": "git+https://github.com/timmh/react-native-camera.git",
    "react-native-facebook-login": "^1.0.2",
    "react-native-google-app-invites": "^0.2.5",
    "react-native-scrollable-tab-view": "^0.3.3",
    "rn-camera-roll": "0.0.2"
  }

**Comment by iamladi** [comment]
And are you using NPM version 3.x?

**Comment by guillaumemorin** [comment]
nope. npm 2.14.15

**Comment by iamladi** [comment]
I've made small change with index.js and that might help. Try installing new version. If that will not help I would recommend you upgrade to npm 3.x. That's what I'm using.

**Comment by guillaumemorin** [comment]
Well, I'm sorry @martincik ... I'm stupid! I think that the problem was only due to the fact that I didn't restart the react manager terminal after npm i. Even if I think that it's better to have to maintain only one index.js (so this is a good improvement at least...), I'm sorry for this anyway! Everything is now working well! Well done, this is a really great work ! and thx for support too ;)

**Comment by iamladi** [comment]
No problem. :) I'm happy it's working. Take care @guillaumemorin.
